### ISSUE TITLE
Adding Show If

### ISSUE THREAD

**Issue by tabunan** [marekmensa/vue-dd-form#1]
Thanks for sharing this package.

I just wondering how to implement showing fields or groups when selecting an option or thick.

**Comment by marekmensa** [comment]
Hi @tabunan,

thanks for your question. This is a pretty regular usage of dd-form. You can do this via `:functions` property. All is shown [here in docs](https://github.com/marekmensa/vue-dd-form#dynamic-values).

1. initialize the `:functions` prop
2. add new function which returns true, if the tick or option is selected (eg. return yourDataSet.yourTick)
3. now you can reference this function's key in description of the view you want to hide (in _hidden_ property)

I could explain closer if I saw your data set or code. Hope this helps!


---

You can see it in action in [demo](https://marekmensa.github.io/vue-dd-form/) – tab **Dynamic values**. Component of the demo is [here](https://github.com/tabunan/vue-dd-form/blob/master/docs-src/components/Home.vue) and descriptions for the tab [here](https://github.com/marekmensa/vue-dd-form/blob/master/docs-src/assets/descriptions-dynamic.json).
