### ISSUE TITLE
Replacing common element ids

### ISSUE THREAD

**Issue by tabunan** [marekmensa/vue-dd-form#2]
Hello, I hope you can also add an option to add a prefix for element ids like for .row, .button and etc.

Thanks

**Comment by marekmensa** [comment]
Hi,

I did probably not get this question, could you clearify?

You can currently assign any custom class names to any view via descriptions. Just add `class: "yourClassName"` to description of desired view. You can also use [Dynamic values](https://github.com/marekmensa/vue-dd-form#dynamic-values), so you can assign it a with a prefix eg. `class: ".row-{_classNameFunction}"`
