### ISSUE TITLE
LabelValue undefine when use view type 'Tick'

### ISSUE THREAD

**Issue by ElNath11** [marekmensa/vue-dd-form#3]
Hai, I have an issue here about Tick type, when I use that type it is not allowed me to render my projects, and the console show me this message

![image](https://user-images.githubusercontent.com/16522776/125580097-7385cb09-3409-480c-9116-9675527d5fa2.png)

please anyone here,

**Comment by marekmensa** [comment]
Thank you for your question. I suppose this is not current anymore but it seems like you did not fill the `label` property in the descriptions, which is required.
