### ISSUE TITLE
vuedraggable.common.js - deprecated message

### ISSUE THREAD

**Issue by yura-x** [marekmensa/vue-dd-form#4]
Hello!
Thanks for your great form component for Vue.js. It is the best auto generated from that I found.
I have noticed that there is a console warning when using your great component.

`
vuedraggable.common.js:2141 Options props is deprecated, add sortable options directly as vue.draggable item, or use v-bind. See https://github.com/SortableJS/Vue.Draggable/blob/master/documentation/migrate.md#options-props
`

[https://github.com/SortableJS/Vue.Draggable/blob/master/documentation/migrate.md#options-props](https://github.com/SortableJS/Vue.Draggable/blob/master/documentation/migrate.md#options-props)

**Comment by marekmensa** [comment]
Hi,

Thank you for your kind words. Are you using vuedraggable in your project, outside of `vue-dd-form`? It seems that the newer version, which you have probably installed, has few properties tagged as deprecated. Update of the `vuedraggable` library will be included for upcoming release of `vue-dd-form`.

Marek

**Comment by yura-x** [comment]
Hello!

Thanks for your reply!

The only component that I'm using is `vue-dd-form`.
I'm using it with my custom PHP project to create dynamic fields from the JSON config file so for now I just included it from the CDN like so:
```
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
<script src="https://unpkg.com/vue-dd-form@1.0.20/dist/vue-dd-form.js"></script>
```
Hope this info will helps you somehow.

Best regards!

**Comment by marekmensa** [comment]
I somehow can not simulate the warning even while using the CDN version. Can you please attach a wider preview?

Also, as I said, upcoming release of `vue-dd-form` will include a migration to newer version of `vuedraggable`. This should definitely solve the issue, so stay tuned!

**Comment by yura-x** [comment]
I will definitely stay tuned because there is no any alternative with sortable dynamic forms - they are so great!
Here is a screenshot:
[https://i.imgur.com/nPWZav2.png](https://i.imgur.com/nPWZav2.png)

Here is a script:
```
<template>
<div data-vue="true" class="vue-app">
	<div id="app-61af6acf22886">
		<div v-cloak="">
			<input type="hidden" v-model="jsonString" name="dynamic_fields">
			<dd-form :data="json" :descriptions="description" :lang="customLang" :functions="functions" @change="change">
			</dd-form>
		</div>
	</div>

</div>
</template>

<script>
new Vue({
	el: '#app-61af6acf22886',
	delimiters: ['~{', '}~'],
	data: function() {
		return {
			json: {},
			jsonString: '',
			description: {
				"fields": {
					"view": "collection",
					"label": "Item Type Fields",
					"addable": true
				},
				"fields[*]": {
					"view": "group",
					"label": "{_fieldTitle}. Field {_fieldIndex}"
				},
				"fields[*].label": {
					"view": "text",
					"label": "Field label (title)"
				},
				"fields[*].name": {
					"view": "text",
					"label": "Field name (slug)"
				},
				"fields[*].type": {
					"view": "select",
					"label": "Field type",
					"options": [
						{
							"text": "Text",
							"value": "text"
						},
						{
							"text": "Password",
							"value": "password"
						},
						{
							"text": "URL",
							"value": "url"
						},
						{
							"text": "Checkbox",
							"value": "checkbox"
						}
					]
				},
			},
			customLang: {
				save: 'Continue',
				add: '+ Add Field'
			},
			functions: {
				'_fieldIndex': this.fieldIndex,
				'_fieldTitle': this.fieldTitle
			}
		}
	},
	computed: {
	},
	methods: {
		change({  path, data }) {
			this.jsonString = JSON.stringify(data);
		},
		splitPath(path) {
			return path.split(/[.[\]]/);
		},
		fieldIndex({ path }) {
			const index = Number(this.splitPath(path)[1]);
			return index + 1;
		},
		fieldTitle: function (path) {
			return path.value.label ? path.value.label : 'Field';
		}
	},
	created: function ()  {
		this.json = {"fields":[{"name":"login","slug":"login","type":"text","label":"Login"},{"name":"pw","slug":"test_passw","type":"password","label":"Password"}]};
		this.jsonString = JSON.stringify( {"fields":[{"name":"login","slug":"login","type":"text","label":"Login"},{"name":"pw","slug":"test_passw","type":"password","label":"Password"}]} );
	}
});
</script>
```

Once again, thank you so much for your component!
Best regards!

**Comment by marekmensa** [comment]
@yura-x Version 1.0.21 with deprecation patch is now available. Try it out and hopefully it will be resolved on your side 🙂

--

I'm glad the component is helping you out, thank you for your support!

**Comment by yura-x** [comment]
Hello, @marekmensa !

With this CDN version there is no warnings now:

https://unpkg.com/vue-dd-form@1.0.21/dist/vue-dd-form.js

Thank you very much!
